[build]
  publish = "."

# Serve /pokemon from pokemon folder
[[redirects]]
  from = "/pokemon"
  to = "/pokemon/index.html"
  status = 200

[[redirects]]
  from = "/pokemon/"
  to = "/pokemon/index.html"
  status = 200

[[redirects]]
  from = "/pokemon/*"
  to = "/pokemon/:splat"
  status = 200
